# ssh-keygen -m pem -t rsa -b 4096 -C org/repo -f deploy_key

# YAML anchors for base definitions
base_def: &base_def
  docker:
    - image: node:14
  working_directory: ~/repo
  environment:
    - DEVELOPMENT_BRANCH: develop
    - PRODUCTION_BRANCH: master

restore_cache_def: &restore_cache_def
  # Download and cache dependencies
  keys:
  - v1-dependencies-{{ checksum "package.json" }}
  - v1-dependencies-  # fallback if checksum fails

##
## START Circle CI configuration
##

version: 2.1
jobs:
  prepare:
    <<: *base_def
    steps:
      - checkout
      - restore_cache:
          <<: *restore_cache_def
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  lint:
    <<: *base_def
    steps:
      - checkout
      - restore_cache:
          <<: *restore_cache_def
      - run: yarn lint
      - run: yarn lint:css
  test:
    <<: *base_def
    steps:
      - checkout
      - restore_cache:
          <<: *restore_cache_def
      - run: yarn test
  build:
    <<: *base_def
    steps:
      - checkout
      - restore_cache:
          <<: *restore_cache_def
      - run: yarn build
      - persist_to_workspace:
          root: ~/repo
          paths:
              - dist/*
  deploy-surge:
    <<: *base_def
    steps:
      - checkout
      - restore_cache:
          <<: *restore_cache_def
      - attach_workspace:
          at: /workspace
      - run:
          name: Deploy to surge
          command: |
            cp /workspace/dist/index.html /workspace/dist/200.html
            # Enable to use surge deployment
            # CIRCLE will need the surge login variables:
            # SURGE_LOGIN & SURGE_TOKEN
            #./node_modules/surge/lib/cli.js --project /workspace/dist --domain <the domain>.surge.sh

workflows:
  version: 2
  main:
    jobs:
      - prepare
      - lint:
          requires:
            - prepare
      - test:
          requires:
            - prepare
      - build:
          requires:
            - prepare
      - deploy-surge:
          requires:
            - lint
            - test
            - build
          filters:
            branches:
              only: master
